name: build

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.bbcode"
      - LICENSE
      - ".github/FUNDING.yml"
    branches: [main, dev]
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.bbcode"
      - LICENSE
      - ".github/FUNDING.yml"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies (apt)
        run: sudo apt install -y libx11-dev libxcursor-dev libpng-dev
        continue-on-error: false

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Caching yarn packages
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set Up NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Caching pip packages
        uses: actions/cache@v2
        id: pip-cache # use this to check for `cache-hit` (`steps.pip-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Generating `Bibata-Bee-Modern` Cursor Theme
        run: make modern

      - name: Compressing `Bibata-Bee-Modern` Cursor Theme
        run: tar -cvzf Bibata-Modern.tar.gz themes/*

      - name: Uploading `Bibata-Bee-Modern` Bitmaps artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Bee-Modern-Bitmaps
          path: bitmaps/*

      - name: Uploading `Bibata-Bee-Modern` Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Bee-Modern
          path: Bibata-Bee-Modern.tar.gz

      - name: Generating `Bibata-Bee-Original` Cursor Theme
        run: make original

      - name: Compressing `Bibata-Bee-Original` Cursor Theme
        run: tar -cvzf Bibata-Bee-Original.tar.gz themes/*

      - name: Uploading `Bibata-Bee-Original` Bitmaps artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Bee-Original-Bitmaps
          path: bitmaps/*

      - name: Uploading `Bibata-Bee-Original` Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bibata-Bee-Original
          path: Bibata-Bee-Original.tar.gz
